# .github/workflows/feature_extraction.yml
name: Feature Extraction and Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extract_and_generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Adjust Python version if needed

    - name: Install dependencies
      run: |
        sudo apt-get install -y libsndfile1  # Install libsndfile
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install soundfile  # Install Python soundfile package

    - name: Extract Features and Generate Track
      run: |
        python scripts/extract_features.py

    - name: Commit and Push Generated Track
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add output/new_darkpsy_track.wav
        git commit -m 'Add generated Darkpsy track'
        git push
