# .github/workflows/tempo_detection.yml
name: Tempo Detection

on:
  push:
    branches:
      - main

jobs:
  detect_tempo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install librosa

    - name: Find Tempo/BPM
      run: |
        python tempo_detection.py

