name: Tempo Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-tempo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # Ensure Git LFS is used

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install librosa soundfile

      - name: Detect Tempo
        run: |
          python scripts/tempo_detection.py audio/CINDERVOMIT.wav
