name: Darkpsy Audio Analysis

on:
  push:
    branches:
      - main  # Adjust this according to your branch

jobs:
  analyze_audio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose Python version
        
    - name: Install dependencies
      run: |
        pip install numpy scipy matplotlib
        
    - name: Run Analysis Script
      run: |
        python scripts/tempo_detection.py audio/CINDERVOMIT.wav
      
    - name: Commit Analysis Results
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add your_darkpsy_file_frequency_spectrum.png
        git commit -m "Add frequency spectrum analysis results"
        git push origin main


